**Linear Algera Assignment**

In [ ]:
import numpy as np

In [ ]:
A = np.array([[1,1,0,0],[0,1,1,0],[0,0,1,1],[1,0,0,1]])
B = np.array([[50],[30],[40],[60]])

In [ ]:
X = np.array([[10],[40],[-10],[50]])

## Finding Norm

In [ ]:
X2 = 0
for i in range (len(X)):
  X2 = X2 + X[i]**2
print("Euclideam Norm (L^2 Norm):", X2**(1/2))

Euclideam Norm (L^2 Norm): [65.57438524]


In [ ]:
X1 = 0
for i in range (len(X)):
  X1 = X1 + abs(X[i])
print("1 Norm:", X1)

1 Norm: [110]


In [ ]:
Xinf = max(X)
print("Infinity Norm:", Xinf)

Infinity Norm: [50]


## Finding Rank of Matrix A and A|B

In [ ]:
A[3] = A[3]-A[0]    # R4-R1
B[3] = B[3]-B[0]
A,B

(array([[ 1,  1,  0,  0],
        [ 0,  1,  1,  0],
        [ 0,  0,  1,  1],
        [ 0, -1,  0,  1]]),
 array([[50],
        [30],
        [40],
        [10]]))

In [ ]:
A[3] = A[3]+A[1]    # R4+R2
B[3] = B[3]+B[1]
A,B

(array([[1, 1, 0, 0],
        [0, 1, 1, 0],
        [0, 0, 1, 1],
        [0, 0, 1, 1]]),
 array([[50],
        [30],
        [40],
        [40]]))

In [ ]:
A[3] = A[3]-A[2]    # R4-R3
B[3] = B[3]-B[2]
A,B

(array([[1, 1, 0, 0],
        [0, 1, 1, 0],
        [0, 0, 1, 1],
        [0, 0, 0, 0]]),
 array([[50],
        [30],
        [40],
        [ 0]]))

As there are 3 non zero rows in both A and A|B Matrix therefore:
**Rank A = Rank A|B = 3**

##  Rank-Nullity of matrix

In [ ]:
columns = 4
Rank_A = 3
print(" Rank-Nullity of matrix = ",columns-Rank_A)

 Rank-Nullity of matrix =  1
